ui-settings:
  exit-button-material: BARRIER
  back-button-material: BARRIER
  next-button-material: BOOK
  previous-button-material: BOOK
  show-packages-head-id: '54098'
  packages-icon-head-id: '54098'
  collect-package-head-id: '22840'
  send-package-head-id: '24849'

post-settings:
  package-expiry-seconds: 604800
  return-package-expiry-seconds: 2592000

save-duration-seconds: 600